- src/events/guild_member_addition.rs
This is a pretty useless feature as nobody looks at #user-log anyways, but it looks nicer ¯\_(ツ)_/¯
Example: 
Editors Note: Yes, that's the official OSHA "Warning" color.
> changes the widget color of guild_member_addition when the user is younger than 3 days

- src/commands/small.rs
profile-commands now have a `clear` subcommand to clear the value. Additionally, they use a normal reply_embed rather than reply_success, thus not send :poggersphisch: when providing values.
Fixes #33
> Add clear for profile commands and make them use normal embeds

- src/commands/top.rs
backticks do not count as quotes, apparently....
> fix top regex not working with multiple words

- src/commands/info.rs
#41 This is what it looks like right now, I thought it was a good idea to just reuse the method
https://user-images.githubusercontent.com/26347830/112706347-e2c05100-8ea3-11eb-8d69-e4460c60ee74.png
> Make info print out the actual date time of joining and account creation

- src/commands/fetch/fetch.rs
Removes text emoticon ":/" so it follows the same reply pattern of other fail/success messages.
> Fix minor fetch message inconsistency.

- .gitignore
- flake.nix
depends on #25 
nix flakes users can use `nix develop`  instead of `nix-shell`
> add nix flake support

- src/db/mod.rs
- src/main.rs
This PR runs the database migrations on bot startup. This should allow us to fully automate deployment via CI!
> Run DB migrations on bot startup

- src/util.rs
[`format_count`](https://github.com/unixporn/trup-rs/blob/13809f71cf32606812aec38fa75dbe65f8325853/src/util.rs#L70) only worked for single digit numbers.
> Fixed format_count

- Cargo.toml
- src/commands/highlights.rs
- src/db/highlights.rs
- src/db/mod.rs
- src/events/message.rs
this PR improves the performance of highlights by first checking with a large regex in the shape of `\b(?:trigger|trigger2|trigger3|trigger4)\b` and using that for the match - thus also allowing for multi-word triggers.
> Improve highlight performance

- src/commands/highlights.rs
Fixes: #146
Instead of removing `!hl ls` invocations, send it in DMs instead since the feature requires DMs anyway.
> make `!hl ls` send you a DM instead

- src/events/message_create.rs
> ignore highlights when in a channel that the user cannot see

- src/checks.rs
The other message is capitalized, this one was not.
> src/checks: fix inconsistent error message

- src/commands/fetch/fetch.rs
- src/commands/fetch/mod.rs
- src/commands/fetch/setfetch.rs
- src/commands/top.rs
- src/db/fetch.rs
- src/events/message_create.rs
* internally use an enum for fetch fields
* add fetch field aliases
Sorry I took so long on this! I implemented `FromString` for the new `FetchField` enum so it can be used with serenity's `Args::single_quoted()` as well as include aliases for different field names. Multiword field names don't seem to work just because of serenity's args thing though; let me know if there's a way to work around this (or anything else I need to fix/clean up/etc) and I'll gladly add it.
> change fetch fields to enum, add aliases

- Cargo.lock
- Cargo.toml
- src/commands/ban.rs
- src/commands/fetch/fetch.rs
- src/commands/help.rs
- src/commands/info.rs
- src/commands/kick.rs
- src/commands/modping.rs
- src/commands/mute.rs
- src/commands/note.rs
- src/commands/pfp.rs
- src/commands/role.rs
- src/commands/unban.rs
- src/commands/warn.rs
- src/embeds.rs
- src/events/handle_blocklist.rs
- src/events/message_create.rs
- src/events/message_delete.rs
- src/events/message_update.rs
- src/extensions.rs
- src/main.rs
- src/util.rs
- Migrate to serenity next, reimplement pagination manually
- Async pagination
This PR migrates to serenitys `next` branch. There, threads are fully supported,
thus functionality that works outside of threads should now also work inside threads.
It also reimplements pagination manually, as serenity_utils does not work on next yet
> Switch to serenity next, thus supporthing threads

- gen-env.sh
If you left the script as is, it would not say "please fill in your token & serverid"
Instead of checking for an empty variable,
check the length of the token (>= 50char)
and check if serverid is a number (>= 999)
> Improve error handling in gen-env.sh

- gen-env.sh
Instead of having to modify the script, you should be able to
just run it and paste the token/serverid
Also made it print the notices / links, instead of having them as a comment
inside of the script.
> Add fancy input for token/serverid

- fetcher.sh
```
Examples:
Linux 5.13.13-arch1-1    -> Linux (arch)
Linux 4.4.0-31-generic   -> Linux (vanilla)
Linux 5.14.1             -> Linux (vanilla)
Linux 5.15.0-rc3-next-20210930-1.gd782f60-vanilla -> Linux (rc)
Linux 5.10.16-zen1-1-zen -> Linux (zen)
Darwin 20.3.0            -> Darwin
```
> Change from kernel version to kernel name & variant

- src/commands/help.rs
- src/commands/move_users.rs
- src/commands/note.rs
- src/commands/pfp.rs
- src/embeds.rs
- src/extensions.rs
This PR adds support for viewing both server and user specific profile pictures with the `!pfp` command. It also changes PaginatedFieldsEmbed to be more generic (PaginatedEmbed) so that it can be used for non-textual embeds.
> Use server specific profile picture in pfp command

- src/commands/pfp.rs
When running `pfp`,  only show multiple images if the server specific pfp and the global pfp are different
> Only show multiple pfps if there is a server specific one

- src/checks.rs
- src/commands/ban.rs
- src/db/highlights.rs
This PR adds the option to ban multiple users via `!ban id,id2,id3,id4,... reason`.
It also changes the ban restrictions for helpers to be based on the join date
> Implement mass banning users (implements #289 and implements #305)

- crates/robbb/src/error_handling.rs
- crates/robbb_util/src/util.rs
This PR adds the root cause to the logs of any errors.
This is mostly useful so we can more easily track errors in honeycomb, 
checking for commonly occuring root causes and finding out what consequences those have.
> Add the root cause to any anyhow error logs

- crates/robbb_commands/src/commands/fetch/mod.rs
fix: arch logo doesn't appear because of the old logo link doesn't work anymore
new image link is from the official arch website
> fix: arch logo doesn't appears

- crates/robbb_commands/src/commands/modping.rs
/modping is used when immediate moderation is required, but moderators currently tend to make themselves unavailable, so the bot only pings helpers.
This change ensures that at least one moderator is pinged by pinging all online moderators, or all moderators in case none are online, and also pinging all online helpers.
This change is not tested, since I have no testing discord, but the change is quite simple.
Please review, test and merge @elkowar
> Ensure at least one actual moderator is pinged
