src/commands/fetch/mod.rs
=> Hide memory value in fetch if it is 0

src/commands/fetch/setfetch.rs
```
!setfetch update
whatever bruh
``` 
did reply with success, as parsing errors in setfetch update where silently ignored. This is now fixed, and it fails with a proper error message
=> Make setfetch update error on invalid format

src/commands/poll.rs
titel.
I can't unsee this now. Please fix!!!!
=> VIC (very important change) - Fixes highly critical bug

src/commands/fetch/fetch.rs, src/commands/fetch/mod.rs, src/db/fetch.rs
=> Order fetch fields manually, and make description a embed description

src/events/message_delete.rs
https://user-images.githubusercontent.com/5300871/112699944-49864000-8e8d-11eb-973a-36367bf85a12.mp4
=> Bot deletes his response if you delete a bot invocation

shell.nix
@buffet i was asked to ask you to check if it's alright
It also requires nixpkgs-unstable :/
=> adds shell.nix

Readme.md
#43 . I'm actually not sure myself what the last 2 env vars are, but I think this is a good starting point. I tried to be as brief, while still providing some info, based on what I was confused about personally when trying to set up a dev environment. Feedback is much appreciated
=> WIP readme explanation of env vars

src/commands/top.rs
This PR adds equivalence-groups to top, meaning that some values such as "neovim" and "vim" will now be considered equal.
This fixes #11
=> Add equivalence-groups to top

src/commands/poll.rs, src/extensions.rs
This should fix #52 and fix #53. This is literally my first attempt at writing Rust code, I would love for some feedback lol.
=> Potential fixes for poll problems

.github/workflows/cargofmt.yaml
It will fail if PR submitters have unformatted code
=> add cargo fmt workflow on push and pull requests

src/attachment_logging.rs, src/commands/ban.rs, src/commands/fetch/mod.rs, src/commands/fetch/setfetch.rs, src/commands/help.rs, src/commands/mute.rs, src/commands/small.rs, src/commands/top.rs, src/events/message.rs, src/events/message_delete.rs, src/events/mod.rs, src/events/ready.rs, src/extensions.rs, src/main.rs, src/util.rs
=> fix clippy warnings

sqlx-data.json, src/commands/info.rs, src/commands/mute.rs, src/db/mute.rs
RFC if this is the best way to do this. If we want to keep all history of mutes, this might be the way to go.
=> WIP #6 mute upsert

src/events/message.rs
The bot will reply when mentioned
This was a thing in trup so added it here as well
just wanted to start contributing tbh :p
=> reply when mentioned

Cargo.lock, Cargo.toml, src/checks.rs, src/extensions.rs
=> nuke #[ext]

.gitignore, src/commands/ban.rs, src/events/message.rs
Closes #75
This is what it looks like for ice
This is what it looks like for normal bans
=> send a different DM when ban reason contains "ice"

src/events/message.rs
Change Repository link from Trup's old one to Robbb's.
=> Updated Repository Link

.github/workflows/docker-publish.yaml, Cargo.lock, Cargo.toml, default.nix, fetcher.sh, flake.nix, src/commands/fetch/setfetch.rs, src/commands/small.rs, src/commands/top.rs, src/events/message_create.rs, src/main.rs
This PR changes links, names in the nix config and the name of the crate to robbb.
As this requires changes in the deployment, confirmation from @mlvzk is required before merging this.
=> Rename stuff from trup-rs to robbb

src/events/handle_blocklist.rs, src/events/message_create.rs, src/events/message_update.rs, src/events/mod.rs
=> Handle blocklist on message update as well

sqlx-data.json, src/db/emoji_logging.rs
yeah you can see it in the server, it doesnt order it
=> fix major ordering bug

sqlx-data.json, src/commands/emojistats.rs, src/db/emoji_logging.rs, src/events/message_create.rs, src/events/mod.rs, src/events/reaction_add.rs, src/events/reaction_remove.rs
=> Fixed  #177 and #178

README.md, gen-env.sh
also fix the name of the README
=> add script to generate environment variables

src/commands/fetch/fetch.rs
you can now do !fetch self wm
to fetch yourself, could be reword to just be s or something similar
=> Added fetch self

src/events/guild_member_update.rs, src/events/mod.rs, src/events/ready.rs
=> Add automatic dehoisting of members on server start and member update

src/commands/highlights.rs
implements #180 
It doesn't need to DM for this right?
=> add a !hl clear command

Cargo.lock
=> Revert "Bump serde_json from 1.0.69 to 1.0.70"

src/commands/pfp.rs
This PR changes the title in the `pfp` command to show the user's tag
=> Change title in pfp command

Cargo.lock, src/events/message_delete.rs, src/events/mod.rs, src/main.rs
72d473a93219bf86d8ef76c6d1772c0ff1f1fb71 to 72d473a93219bf86d8ef76c6d1772c0ff1f1fb71
=> Update serenity to fix broken build

Cargo.lock, Cargo.toml, src/attachment_logging.rs, src/commands/ban.rs, src/embeds.rs, src/events/ready.rs, src/main.rs
Fix logging issues and allow the use of RUST_LOG to specify logging levels
Also finish migrating from log to tracing 
woo
=> Configure honeycomb tracing with RUST_LOG, migrate to tracing 

Cargo.lock, Cargo.toml, src/commands/ask.rs, src/commands/ban.rs, src/commands/fetch/fetch.rs, src/commands/help.rs, src/commands/info.rs, src/commands/kick.rs, src/commands/modping.rs, src/commands/mute.rs, src/commands/note.rs, src/commands/pfp.rs, src/commands/role.rs, src/commands/unban.rs, src/commands/warn.rs, src/events/handle_blocklist.rs, src/events/message_create.rs, src/events/message_delete.rs, src/events/mod.rs, src/extensions.rs, src/main.rs
This PR migrates back to serenity main, hoping that that will reduce the amount of weird issues we encounter. we initially switched to next because we needed thread support -- which is now in main
=> Migrate to serenity main

src/commands/mod.rs
=> add user matching via `user#1234`

src/commands/highlights.rs
Fixes #316 
Actually matching on the error kind is not worth just for this imo
=> improved "highlight add" error msg

src/commands/blocklist.rs
=> Improve blocklist add / remove error messages

src/events/message_create.rs
=> Send highlights from ask commands

src/commands/move_users.rs
This PR adds a special case for the command `!move` when used with `#tech-support`.
The bot will respond with: 
```
Please <users...> use !ask to ask your question in #tech-support
```
Instead of the normal
```
MOVE THIS CONVERSATION!
Continued at #tech-support: [Conversation]
Please continue your conversation there!
```
=> Add special case !move #tech-support

crates/robbb/src/events/guild_member_removal.rs
Simple change to remove HTM from DB if the User doesn't have HTM at the time of removal.
=> feat: remove htm from db if user doesn't have htm at time of leaving
